if node['ec2']
  prefix = 'myusa/' + node['myusa']['rails_env']
  node.set['myusa']['secrets']['db_encrypt_key'] = citadel["#{prefix}/db_encrypt_key"]
  node.set['myusa']['secrets']['devise_secret_key'] = citadel["#{prefix}/devise_secret_key"]
  node.set['myusa']['secrets']['smtp_user'] = citadel["#{prefix}/smtp_user"]
  node.set['myusa']['secrets']['smtp_pass'] = citadel["#{prefix}/smtp_pass"]
  node.set['myusa']['secrets']['omniauth_google_app_id'] = citadel["#{prefix}/google_client_id"]
  node.set['myusa']['secrets']['omniauth_google_secret'] = citadel["#{prefix}/google_client_secret"]
  node.set['myusa']['secrets']['newrelic_key'] = citadel["#{prefix}/newrelic_key"]
  node.set['myusa']['secrets']['secret_key_base'] = citadel["#{prefix}/secret_key_base"]
  node.set['myusa']['ssl']['cert'] = citadel["#{prefix}/internal_cert"]
  node.set['myusa']['ssl']['key'] = citadel["#{prefix}/internal_cert_key"]
  node.set['myusa']['secrets']['twilio_account_sid'] = citadel["#{prefix}/twilio_account_sid"]
  node.set['myusa']['secrets']['twilio_auth_token'] = citadel["#{prefix}/twilio_auth_token"]
end
